/* This file was generated by SableCC (http://www.sablecc.org/). */

package smile.node;

import smile.analysis.*;

@SuppressWarnings("nls")
public final class APrintcharStmt extends PStmt
{
    private TPrintchar _printchar_;

    public APrintcharStmt()
    {
        // Constructor
    }

    public APrintcharStmt(
        @SuppressWarnings("hiding") TPrintchar _printchar_)
    {
        // Constructor
        setPrintchar(_printchar_);

    }

    @Override
    public Object clone()
    {
        return new APrintcharStmt(
            cloneNode(this._printchar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrintcharStmt(this);
    }

    public TPrintchar getPrintchar()
    {
        return this._printchar_;
    }

    public void setPrintchar(TPrintchar node)
    {
        if(this._printchar_ != null)
        {
            this._printchar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._printchar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._printchar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._printchar_ == child)
        {
            this._printchar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._printchar_ == oldChild)
        {
            setPrintchar((TPrintchar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
