/* This file was generated by SableCC (http://www.sablecc.org/). */

package smile.node;

import smile.analysis.*;

@SuppressWarnings("nls")
public final class TInputchar extends Token
{
    public TInputchar()
    {
        super.setText(":-O");
    }

    public TInputchar(int line, int pos)
    {
        super.setText(":-O");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInputchar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInputchar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInputchar text.");
    }
}
