/* This file was generated by SableCC (http://www.sablecc.org/). */

package smile.node;

import smile.analysis.*;

@SuppressWarnings("nls")
public final class TPrintchar extends Token
{
    public TPrintchar()
    {
        super.setText(":-@");
    }

    public TPrintchar(int line, int pos)
    {
        super.setText(":-@");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrintchar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrintchar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrintchar text.");
    }
}
