/* This file was generated by SableCC (http://www.sablecc.org/). */

package smile.node;

import smile.analysis.*;

@SuppressWarnings("nls")
public final class TWhileend extends Token
{
    public TWhileend()
    {
        super.setText("O_o");
    }

    public TWhileend(int line, int pos)
    {
        super.setText("O_o");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWhileend(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWhileend(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWhileend text.");
    }
}
