/* This file was generated by SableCC (http://www.sablecc.org/). */

package smile.analysis;

import smile.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAStmtlist(AStmtlist node);
    void caseAEmptyStmtlist(AEmptyStmtlist node);
    void caseANextindexStmt(ANextindexStmt node);
    void caseAPrevindexStmt(APrevindexStmt node);
    void caseAIncStmt(AIncStmt node);
    void caseADecStmt(ADecStmt node);
    void caseAPrintStmt(APrintStmt node);
    void caseAPrintcharStmt(APrintcharStmt node);
    void caseAWhileStmt(AWhileStmt node);
    void caseAIfStmt(AIfStmt node);

    void caseTNextindex(TNextindex node);
    void caseTPrevindex(TPrevindex node);
    void caseTInc(TInc node);
    void caseTDec(TDec node);
    void caseTWhileint(TWhileint node);
    void caseTWhileend(TWhileend node);
    void caseTPrint(TPrint node);
    void caseTPrintchar(TPrintchar node);
    void caseTIf(TIf node);
    void caseTEndif(TEndif node);
    void caseTNewLine(TNewLine node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
}
